[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish
  publish = "frontend/dist"
  
  # Base directory for the build
  base = "frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
